pub mod acp;
pub mod agent_setup;
pub mod agents;
pub mod automations;
pub mod avatars;
pub mod distro;
pub mod doctor;
pub mod git;
pub mod git_changes;
pub mod layout;
pub mod migration;
pub mod model_setup;
pub mod openai_realtime;
pub mod path_resolver;
pub mod project_assets;
pub mod project_icons;
mod sse;
pub mod system;
